### ISSUE TITLE
Building electron app's appdmg module failed on Mac x86 and arm64 platforms

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai-webui#1575]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

main

### Describe the bug

When building Backend.AI webui's electron app, I found installing package stage errors.

Mac platform Both x86 and arm64 show  'appdmg' module error during build electron app.

However, It doesn't found 'appdmg' module error on Linux(x86_64)  It works only Linux x86.

ps. Surprisingly, 'make test_electron' works even if the building app fails on the mac.

That electron version is v14.2.9 and node version is v19.6

Packaging app for platform darwin arm64 using electron v14.2.9

* mac_Intel
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/20002/217172062-fd60f738-5419-4e71-bdf8-ba25972227ed.png">

```
[BUILD] Now packaging for darwin with x64 architecture.

Packaging app for platform darwin x64 using electron v14.2.9

[BUILD] Done.

rm -rf ./app/backend.ai-desktop-macos-intel
cd app; mv "Backend.AI Desktop-darwin-x64" backend.ai-desktop-macos-intel;
./node_modules/electron-installer-dmg/bin/electron-installer-dmg.js './app/backend.ai-desktop-macos-intel/Backend.AI Desktop.app' ./app/backend.ai-desktop-intel-230207 --overwrite --icon=manifest/backend-ai.icns --title=Backend.AI
node:internal/modules/cjs/loader:1060
  const err = new Error(message);
              ^

Error: Cannot find module 'appdmg'
Require stack:
- /Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js
- /Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/bin/electron-installer-dmg.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at build (/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js:9:18)
    at module.exports (/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js:122:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js',
    '/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/bin/electron-installer-dmg.js'
  ]
}

Node.js v19.6.0
Makefile:90: recipe for target 'mac_intel' failed
make: *** [mac_intel] Error 1
```

* mac_apple
![image](https://user-images.githubusercontent.com/20002/217172273-87b4e400-1c8c-439e-93c7-cc3346b9e14d.png)

```
[BUILD] Now packaging for darwin with arm64 architecture.

Packaging app for platform darwin arm64 using electron v14.2.9

[BUILD] Done.

rm -rf ./app/backend.ai-desktop-macos-apple
cd app; mv "Backend.AI Desktop-darwin-arm64" backend.ai-desktop-macos-apple;
./node_modules/electron-installer-dmg/bin/electron-installer-dmg.js './app/backend.ai-desktop-macos-apple/Backend.AI Desktop.app' ./app/backend.ai-desktop-apple-230207 --overwrite --icon=manifest/backend-ai.icns --title=Backend.AI
node:internal/modules/cjs/loader:1060
  const err = new Error(message);
              ^

Error: Cannot find module 'appdmg'
Require stack:
- /Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js
- /Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/bin/electron-installer-dmg.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at build (/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js:9:18)
    at module.exports (/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js:122:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/src/index.js',
    '/Users/dhsung/dev/backend.ai-webui-import-git-url/node_modules/electron-installer-dmg/bin/electron-installer-dmg.js'
  ]
}

Node.js v19.6.0
Makefile:104: recipe for target 'mac_apple' failed
make: *** [mac_apple] Error 1
```

### Expected Behavior

run the electron app and make dmg installing files on Mac OS(both x86_64 and arm64)

**Comment by studioego** [comment]
I checked the building app module on Linux. It works.
![image](https://user-images.githubusercontent.com/20002/217181810-0a6198bd-2a1f-473b-931b-f1acbe4bceda.png)

**Comment by studioego** [comment]
I found the related issue post on web.

[이슈 8 Error: Cannot find module 'source-map-support/source-map-support.js'](https://roomedia.tistory.com/entry/Error-Cannot-find-module-source-map-supportsource-map-supportjs)

After I run `yarn`  and `npm i`, It works and makes installing mac package file `dmg`. 
<img width="1518" alt="스크린샷 2023-02-07 오후 4 58 00" src="https://user-images.githubusercontent.com/20002/217438349-bbf25194-ccc1-470a-bf74-2a243afb1308.png">
<img width="1519" alt="스크린샷 2023-02-07 오후 4 59 18" src="https://user-images.githubusercontent.com/20002/217438388-7e0058b3-9fb3-4dfb-bdf3-0458118be235.png">


I think that some npm package have not been download correctly. 
If this issue occurs again, I'll open it.
